background {
    monitor =
    path = /home/seth/wall/wall2.png
    blur_passes = 2
    blur_size = 7
    brightness = 0.5
}

input-field {
    monitor =
    size = 250, 40
    outline_thickness = 1
    outer_color = rgb(304B54)
    inner_color = rgb(050D11)
    font_color = rgb(a8b5bc)
    fade_on_empty = true
    placeholder_text = <span>󰌾 password</span>
    fail_color = rgb(c084fc)
    fail_text = <i>wrong password</i>
    capslock_color = rgb(0C6CB4)
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<b>$(date +"%H:%M")</b>"
    color = rgba(a8b5bcff)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = rgba(537787ff)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 20
    halign = center
    valign = center
}
